#include <iostream.h>
#include <conio.h>
void main ()
{int BiL1, BiL2;

cout<<"Masukkan Bilangan Pertama  : ";
cin>>BiL1;
cout<<"Masukkan Bilangan Kedua  : ";
cin>>BiL2;
cout<<"Hasil "<<BiL1<<" + "<<BiL2<<" = "<<(BiL1+BiL2);
cout<<"Hasil "<<BiL1<<" - "<<BiL2<<" = "<<(BiL1-BiL2);
cout<<"Hasil "<<BiL1<<" * "<<BiL2<<" = "<<(BiL1*BiL2);
cout<<"Hasil "<<BiL1<<" / "<<BiL2<<" = "<<(BiL1/BiL2);
cout<<"Hasil "<<BiL1<<" % "<<BiL2<<" = "<<(BiL1%BiL2);
return;
}

